default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: bh_development

test:
  <<: *default
  database: bh_test

production:
  <<: *default
  database: bh_production
