default: &default
  secret_key_base:       <%= ENV['SECRET_KEY_BASE']       %>
  pusher_url:            <%= ENV['PUSHER_URL']            %>
  twilio_account_sid:    <%= ENV['TWILIO_ACCOUNT_SID']    %>
  twilio_auth_token:     <%= ENV['TWILIO_AUTH_TOKEN']     %>
  twilio_app_sid:        <%= ENV['TWILIO_APP_SID']        %>
  twilio_phone_number:   <%= ENV['TWILIO_PHONE_NUMBER']   %>
  sendgrid_password:     <%= ENV['SENDGRID_PASSWORD']     %>
  sendgrid_username:     <%= ENV['SENDGRID_USERNAME']     %>
  braintree_merchant_id: <%= ENV['BRAINTREE_MERCHANT_ID'] %>
  braintree_public_key:  <%= ENV['BRAINTREE_PUBLIC_KEY']  %>
  braintree_private_key: <%= ENV['BRAINTREE_PRIVATE_KEY'] %>
  parse_application_id:  <%= ENV['PARSE_APPLICATION_ID']  %>
  parse_api_key:         <%= ENV['PARSE_API_KEY']         %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
